### ISSUE TITLE
Link to original MS/MS file doesn't work

### ISSUE THREAD

**Issue by cthoyt** [mwang87/MetabolomicsSpectrumResolver#108]
<img width="1131" alt="Screen Shot 2020-07-27 at 17 40 23" src="https://user-images.githubusercontent.com/5069736/88561872-43a33b00-d030-11ea-879e-9839293043fb.png">

The link that comes next to the USI accession doesn't point to the right place. It has "None" in the URL, so this might be an issue with the template.

**Comment by bittremieux** [comment]
Ah, that probably didn't get properly updated when switching from the legacy USIs to the new USIs. Thanks for reporting.

**Comment by cthoyt** [comment]
In general, if there's a python function that takes a USI and generates a URL for either the resource, or to directly download the file, that would be really useful.

Hopefully after you check out #107, it would be more obvious how somebody could make use of functions in this repo :)

**Comment by bittremieux** [comment]
The `parse_usi` function in `parsing.py` returns a tuple of an `MsmsSpectrum` objects and an URL for the resource, so you can get it from there.

We don't provide functionality to download spectrum files because that's not a universal concept across all repositories. GNPS and MassIVE contain raw spectral data and thus deal with files, but for example MS2LDA consists of machine learned MS2 spectra patterns, while Massbank contains individual reference spectra.

The use case for the spectrum resolver wasn't really to provide a stand-alone API, but have it just be the current web resource. We can consider exposing some API functionality, but we'll have to see how to refactor the code somewhat to that extent.
