### ISSUE TITLE
[Bug] Lower Cosine that we should be getting

### ISSUE THREAD

**Issue by mwang87** [mwang87/MetabolomicsSpectrumResolver#180]
https://metabolomics-usi.ucsd.edu/dashinterface/?usi1=mzspec%3APXD000533%3A3B19-1.mzML%3Ascan%3A22121&usi2=mzspec%3APXD022531%3Ab9451_ALCAM.mzXML%3Ascan%3A18869&width=10.0&height=6.0&mz_min=None&mz_max=None&max_intensity=125&annotate_precision=4&annotation_rotation=90&cosine=shifted&fragment_mz_tolerance=2.0&grid=False&annotate_peaks=%5B%5B846.5438232421875%2C%20888.5302734375%5D%2C%20%5B%5D%5D

[Reference Similarity](http://gnps-similarity.ucsd.edu//?usi1=mzspec%3APXD000533%3A3B19-1.mzML%3Ascan%3A22121&usi2=mzspec%3APXD022531%3Ab9451_ALCAM.mzXML%3Ascan%3A18869&peak_tolerance=1&filter_switches=%5B%5D)

**Comment by bittremieux** [comment]
The similarity from the resolver is the same as from matchms, so I don't think there's really an issue. The discrepancy with the GNPS score is because we don't do any preprocessing. Here, this means that the precursor peak in the bottom spectrum will have a large influence, whereas in the GNPS score it's not included.
