### ISSUE TITLE
Improving the fragment m/z value display

### ISSUE THREAD

**Issue by lfnothias** [mwang87/MetabolomicsSpectrumResolver#4]
- First view: Enable the toolbox tip by default
- SVG: Have a user defined value for the m/z intensity threshold.

**Comment by schymane** [comment]
May also need to auto detect appropriate decimal places from input data (if only 1 dp in input, we should not display 4)

**Comment by schymane** [comment]
Also (I'm mobile viewing atm) may need more buffer on y axis so masses don't cross plot border

**Comment by bittremieux** [comment]
Y-axis scaling is a bit annoying. I've looked into ways to do it dynamically within `spectrum_utils`, but that's pretty much impossible because you can't know where the text annotations will end up before painting the figure, and after painting you can't change anything anymore.

In `spectrum_utils` I use 1.05 as y_max when peaks aren't annotated and 1.15 when they are. To properly fit a 7-digit number (4 decimals) the 1.15 might have to be increased a bit.

**Comment by schymane** [comment]
I tend to hard code as well, up to 1.5 for mass annotations and 2.5 if you want formula and structure annotations ... 
The basis of the spectra in here were autogenerated, if you want to get an idea. 2.5 may be overkill but does leave lots of space for annotations ... 
https://link.springer.com/article/10.1007%2Fs00216-019-01885-0

**Comment by sdrogers** [comment]
Could just add parameters for y_min and y_max and let the user tweak if things don't look quite right?
